<a href="https://colab.research.google.com/github/mukulre/Data-Science-Projects/blob/main/10_09_25_E0322052_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
tensor = tf.range(30)
reshaped_tensor = tf.reshape(tensor, [3, 2, 5])

# Display the tensor
print(reshaped_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [ ]:
rank_3_tensor=tf.constant([
    [[0,1,2,3,4],
     [5,6,7,8,9],
    [10,11,12,13,14],
    [15,16,17,18,19],
     [20,21,22,23,24],
     [25,26,27,28,29]],])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(1, 6, 5), dtype=int32)


In [ ]:
tf.reduce_max(rank_3_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=29>

In [ ]:
print(rank_3_tensor.dtype)

<dtype: 'int32'>


In [ ]:
print(rank_3_tensor.ndim)

3


In [ ]:
#print the elements along axis 0 of rank_3_tensor
print(rank_3_tensor[0,:,:])

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [ ]:
#print total no of elements in rank_3_tensor
print(tf.size(rank_3_tensor).numpy())

30
