<a href="https://colab.research.google.com/github/mukulre/Data-Science-Projects/blob/main/Tensorflow_E0322052.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
#Scalar (0D tensor)
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix=tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
tensor= tf.constant([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [9]:
tensor.ndim

3

In [10]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [11]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(3,2))

In [17]:
not_shuffled = tf.constant ([[10, 7], [3, 4], [2, 5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [18]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A
A= tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [19]:
A = tf.constant(numpy_A, shape = (2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [20]:
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [22]:
rank_4_tensor.ndim

4

In [23]:
rank_4_tensor.shape[0]
rank_4_tensor.shape[-1]

5

In [24]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [25]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [26]:
tensor = tf.constant([[10, 7], [3, 4]])
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [29]:
X = tf.constant([[1, 2], [3, 4], [5, 6]])
Y = tf.constant([[7, 8], [9, 10], [11, 12]])
print(X, Y)
tf.matmul(X, Y)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [30]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [31]:
tf.matmul(X, tf.reshape(Y, shape = (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [32]:
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [33]:
B = tf.constant([1.4, 4.5])
B = tf.cast(B, dtype=tf.int16)
B.dtype

tf.int16

In [34]:
E = tf.constant(np.random.randint(0, 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([79, 20, 98, 46, 72, 18, 92, 47, 50,  9, 87, 60, 42,  9, 66, 89, 64,
       18, 13, 30, 63, 50, 14, 38, 17, 68, 14, 96, 58, 64, 22, 41, 28, 25,
       43, 67, 13, 39, 44, 56,  7, 97, 26,  1, 39, 54, 52, 88, 77, 67])>

In [35]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [36]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [37]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [38]:
G_tensor = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G_tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.4669099 , 0.8253486 , 0.48470712, 0.09940028, 0.8480308 ,
           0.47448444, 0.94296277, 0.60900533, 0.17419899, 0.49522066,
           0.43618166, 0.773808  , 0.18450415, 0.19182777, 0.16023076,
           0.18413532, 0.493968  , 0.99080837, 0.57593143, 0.61830366,
           0.9335048 , 0.96679056, 0.36917448, 0.09100091, 0.7697624 ,
           0.7087964 , 0.03019714, 0.815418  , 0.32838833, 0.9521432 ,
           0.0026865 , 0.6417844 , 0.74886215, 0.3931353 , 0.19950843,
           0.99033344, 0.5433805 , 0.5342419 , 0.34179258, 0.6296598 ,
           0.5411192 , 0.40538895, 0.08857703, 0.29820848, 0.8191191 ,
           0.67770195, 0.11177325, 0.11602938, 0.93558884, 0.5887177 ]]]]],
      dtype=float32)>

In [39]:
G_squeezed = tf.squeeze(E)
G_squeezed

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([79, 20, 98, 46, 72, 18, 92, 47, 50,  9, 87, 60, 42,  9, 66, 89, 64,
       18, 13, 30, 63, 50, 14, 38, 17, 68, 14, 96, 58, 64, 22, 41, 28, 25,
       43, 67, 13, 39, 44, 56,  7, 97, 26,  1, 39, 54, 52, 88, 77, 67])>

In [40]:
some_list = [ 0, 1, 2, 3 ]
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>